### ISSUE TITLE
🛠️ `manuscript-cli` needs additional features related to configuration

### ISSUE THREAD

**Issue by KagemniKarimu** [chainbase-labs/manuscript-core#113]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/chainbase-labs/manuscript-core/issues), including closed ones.
- [X] I have searched for existing pull requests [search for existing pull requests](https://github.com/chainbase-labs/manuscript-core/pulls), including closed ones.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

# Rationale
There is currently a lot of limitations on the way in which manuscript-cli handles configuration. The configuration file operating as the single source of truth has several benefits. As per previous PRs and discussions, we are currently in the process of migrating all responsibilities such that this is the case. The goal of this issue is to compile all the suggested changes , spread across different PRs and discussions into a single issue, so that they can be tracked and implemented sequentially.

# Suggested Features 

- [ ] a global `start` command where a user can deploy any manuscript from a config without listing the entire path or parameters for the manuscript in question (this would speed up deploys & make better use of the manuscript_config.ini) (#101 / #108)
- [ ]  a global `--config` flag that allows most commands to run from the specified config file instead of one in the default location ((#101 / #108)
- [ ] a `config` subcommand such as `fix` or `append` which allows adding manuscripts from disk and/or fixing discrepancies of manuscripts which are listed on disk but not in config and vice versa. (NEW!)
- [ ] a hard delete / purging of manuscript files on disk with an additional `--destructive` flag (config clean `-d`) (#108 )
- [ ] Direct manipulation of other configuration settings from the CLI , i.e. (`config --set-base-dir`). Can be accomplished via subcommands which allow line-edits to the config file directly from the CLI ; this would operate similar to how `git config` works.  (#108)

# Explanation

If these features are added, the DX is significantly improved. Once #110 is implemented, state detection logic is restored, and port selection is improved, a user can then script the launch of manuscripts from other applications - test if they're running, and do sophisticated management without having to manually intervene with files on disk.

### 2. Could you assist us with this feature?

- [X] I am interested in contributing to this feature.
